// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// Copyright 2026 The Flutter Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `dispatcher`, `produce_texture_frames`, `register`, `render_gpu_frame`, `render_pixel_frame`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `FixturePlugin`, `TextureState`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `fmt`, `fmt`, `register`

bool synchronousProbe() => RustLib.instance.api.crateApiSynchronousProbe();

Future<DispatchProbe> backgroundDispatchProbe() =>
    RustLib.instance.api.crateApiBackgroundDispatchProbe();

TextureProbe textureProbe() => RustLib.instance.api.crateApiTextureProbe();

bool startTextureProducer() => RustLib.instance.api.crateApiStartTextureProducer();

class DispatchProbe {
  final bool callerWasMainThread;
  final bool callbackWasMainThread;
  final bool synchronousCallbackWasDeferred;

  const DispatchProbe({
    required this.callerWasMainThread,
    required this.callbackWasMainThread,
    required this.synchronousCallbackWasDeferred,
  });

  @override
  int get hashCode =>
      callerWasMainThread.hashCode ^
      callbackWasMainThread.hashCode ^
      synchronousCallbackWasDeferred.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DispatchProbe &&
          runtimeType == other.runtimeType &&
          callerWasMainThread == other.callerWasMainThread &&
          callbackWasMainThread == other.callbackWasMainThread &&
          synchronousCallbackWasDeferred == other.synchronousCallbackWasDeferred;
}

class TextureProbe {
  final PlatformInt64 gpuTextureId;
  final PlatformInt64 pixelTextureId;
  final BigInt gpuFrames;
  final BigInt pixelFrames;

  const TextureProbe({
    required this.gpuTextureId,
    required this.pixelTextureId,
    required this.gpuFrames,
    required this.pixelFrames,
  });

  @override
  int get hashCode =>
      gpuTextureId.hashCode ^ pixelTextureId.hashCode ^ gpuFrames.hashCode ^ pixelFrames.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TextureProbe &&
          runtimeType == other.runtimeType &&
          gpuTextureId == other.gpuTextureId &&
          pixelTextureId == other.pixelTextureId &&
          gpuFrames == other.gpuFrames &&
          pixelFrames == other.pixelFrames;
}
