[package]
name = "flutter-shell-core"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
description = "Private Rust runtime core for the Flutter Rust shell"

[lib]
crate-type = ["rlib", "staticlib"]
path = "src/lib.rs"

[dependencies]
flutter-plugin-sdk = { path = "../flutter-plugin-sdk", version = "0.1.0" }
